#!/bin/bash

dotnet build ./NameServer/NameServer.csproj
dotnet build ./DataNodes/DataNodes.csproj
dotnet build ./FactorsServer/FactorsServer.csproj
dotnet build ./FactorsWorker/FactorsWorker.csproj


dotnet run --project ./NameServer/NameServer.csproj &
sleep 2 
echo "started server"
for i in {1..4}
do
    dotnet run --project ./DataNodes/DataNodes.csproj &
done
echo "datanodes up"
dotnet run --project ./FactorsServer/FactorsServer.csproj &
sleep 2 
echo "loadbalancer"
for i in {1..4}
do
    dotnet run --project ./FactorsWorker/FactorsWorker.csproj &
done
echo "lbworkers up"
# dotnet run --project ./FactorsClient/FactorsClient.csproj --interactive